# Long-form Content Bot Configuration (NIP-23)
# This bot publishes articles and blog posts

bot_name: "Long-form Content Bot"
bot_description: "Publishes long-form articles and blog posts to Nostr"

# Event kind (30023 for long-form content)
event_kind: 30023

# Nostr identity configuration
npub:
  environment_variable: "NOSTR_BOT_KEY1"
  public_key: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"

# Relay configuration
relays: "favorite-relays"  # Use category from relays.yml, or "all", or specific URL

# Article metadata
title: "Getting Started with Nostr"
summary: "A comprehensive guide to understanding and using the Nostr protocol"
image: "https://i.nostr.build/example.jpg"
topics: ["nostr", "decentralization", "social-media", "protocol"]

# Content files to load
content_files:
  markdown: "botData/longFormExample/article.md"

# Optional: Create notification event after publishing
create_notification: true
notification_text: "New article published"

# Optional: NIP-27 references to other events/profiles
references:
  - type: "profile"
    id: "npub1example..."
    relay: "wss://relay.example.com"
  - type: "event" 
    id: "event_id_here"
    relay: "wss://relay.example.com"

# Optional: Custom tags
custom_tags:
  - ["client", "nostrbots"]
  - ["lang", "en"]
