services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-nostrbots
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/madmin/Projects/GitCitadel/Nostrbots:/workspace
    environment:
      - JENKINS_OPTS=--httpPort=8080
    networks:
      - jenkins-network
    restart: unless-stopped

  # Nostrbots build agent
  nostrbots-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: nostrbots:jenkins
    container_name: nostrbots-agent
    volumes:
      - /home/madmin/Projects/GitCitadel/Nostrbots/bots:/app/bots
      - /home/madmin/Projects/GitCitadel/Nostrbots/logs:/app/logs
      - /home/madmin/Projects/GitCitadel/Nostrbots/tmp:/app/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-network
    command: ["tail", "-f", "/dev/null"]

networks:
  jenkins-network:
    driver: bridge
