# Publication Index Bot Configuration (kind 30040)
# This bot creates curated publication indices (table of contents)

bot_name: "Publication Index Bot"
bot_description: "Creates curated publication indices for organized content collections"

# Event kind (30040 for publication index)
event_kind: 30040

# Nostr identity configuration
npub:
  environment_variable: "NOSTR_BOT_KEY"
  public_key: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"

# Relay configuration
relays: "favorite-relays"

# Publication metadata (required)
title: "The Complete Guide to Nostr"
auto_update: true

# Optional publication metadata
author: "Nostr Community"
summary: "A comprehensive guide covering all aspects of the Nostr protocol"
image: "https://i.nostr.build/nostr-guide-cover.jpg"
type: "documentation"  # book, illustrated, magazine, documentation, academic, blog
version: "2.0"
published_by: "Nostr Developers"
published_on: "2024-01-15"
source: "https://github.com/nostr-protocol/nips"
isbn: "9780123456789"  # Will be formatted as i tag

# Topics
topics: ["nostr", "protocol", "documentation", "guide"]

# Content references (sections that make up this publication)
content_references:
  - kind: 30041
    pubkey: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"
    d_tag: "nostr-guide-introduction"
    relay: "wss://thecitadel.nostr1.com"
    event_id: ""  # Optional for version tracking
  - kind: 30041
    pubkey: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"
    d_tag: "nostr-guide-getting-started"
    relay: "wss://thecitadel.nostr1.com"
  - kind: 30041
    pubkey: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"
    d_tag: "nostr-guide-advanced-features"
    relay: "wss://thecitadel.nostr1.com"
  - kind: 30041
    pubkey: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"
    d_tag: "nostr-guide-development"
    relay: "wss://thecitadel.nostr1.com"

# Optional: For derivative works (uncomment if this is based on another work)
# original_author: "npub1original..."
# original_event: "event_id_of_original"

# Custom tags
custom_tags:
  - ["client", "nostrbots"]
  - ["lang", "en"]
  - ["license", "MIT"]
