# Genesis 1:1 Verse - Level 3 (Individual Verse)
# This creates an individual Bible verse as publication content

bot_name: "Bible Publisher - Genesis 1:1"
bot_description: "Creates individual Bible verse content"

# Event kind (30041 for publication content - individual verse)
event_kind: 30041

# Nostr identity configuration
npub:
  environment_variable: "NOSTR_BOT_KEY1"
  public_key: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"

# Relay configuration
relays: "favorite-relays"

# Content metadata
title: "Genesis 1:1"
summary: "In the beginning God created the heaven and the earth."

# Content files to load
content_files:
  content: "botData/bibleExample/genesis-1-1.txt"

# D-tag configuration
static_d_tag: true  # Use consistent d-tag: "genesis-1-1"

# Topics
topics: ["genesis", "creation", "god", "beginning", "verse"]

# Custom tags
custom_tags:
  - ["client", "nostrbots"]
  - ["lang", "en"]
  - ["book", "genesis"]
  - ["chapter", "1"]
  - ["verse", "1"]
  - ["testament", "old"]
  - ["reference", "Genesis 1:1"]
