# Genesis Book Index - Level 1 (Book)
# This creates the Genesis book index with chapters as content references

bot_name: "Bible Publisher - Genesis"
bot_description: "Creates Genesis book index with chapters"

# Event kind (30040 for publication index)
event_kind: 30040

# Nostr identity configuration
npub:
  environment_variable: "NOSTR_BOT_KEY1"
  public_key: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"

# Relay configuration
relays: "favorite-relays"

# Publication metadata
title: "Genesis"
author: "Moses (traditional)"
summary: "The first book of the Bible - Creation, Fall, and the Patriarchs"
type: "book"

# Hierarchy configuration
hierarchy_level: 1  # Book level
parent_index: "the-holy-bible"  # Reference to main Bible index
static_d_tag: true  # Use consistent d-tag: "genesis"

# Topics
topics: ["genesis", "creation", "patriarchs", "old-testament"]

# Content references - Genesis chapters as nested indices
content_references:
  - kind: 30040  # Chapter as index containing verses
    pubkey: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"
    d_tag: "genesis-1"
    relay: "wss://thecitadel.nostr1.com"
    order: 1
  - kind: 30040
    pubkey: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"
    d_tag: "genesis-2"
    relay: "wss://thecitadel.nostr1.com"
    order: 2
  - kind: 30040
    pubkey: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"
    d_tag: "genesis-3"
    relay: "wss://thecitadel.nostr1.com"
    order: 3
  # ... up to Genesis 50

# Custom tags
custom_tags:
  - ["client", "nostrbots"]
  - ["lang", "en"]
  - ["book", "genesis"]
  - ["testament", "old"]
