# Genesis Chapter 1 Index - Level 2 (Chapter)
# This creates the Genesis 1 chapter index with verses as content references

bot_name: "Bible Publisher - Genesis 1"
bot_description: "Creates Genesis Chapter 1 index with individual verses"

# Event kind (30040 for publication index)
event_kind: 30040

# Nostr identity configuration
npub:
  environment_variable: "NOSTR_BOT_KEY1"
  public_key: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"

# Relay configuration
relays: "favorite-relays"

# Publication metadata
title: "Genesis Chapter 1"
author: "Moses (traditional)"
summary: "The Creation Account - In the beginning God created the heavens and the earth"
type: "book"

# Hierarchy configuration
hierarchy_level: 2  # Chapter level
parent_index: 
  d_tag: "genesis"
  pubkey: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"
  relay: "wss://thecitadel.nostr1.com"
static_d_tag: true  # Use consistent d-tag: "genesis-1"

# Topics
topics: ["genesis", "creation", "god", "beginning"]

# Content references - Individual verses as 30041 content sections
content_references:
  - kind: 30041  # Individual verse
    pubkey: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"
    d_tag: "genesis-1-1"
    relay: "wss://thecitadel.nostr1.com"
    order: 1
  - kind: 30041
    pubkey: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"
    d_tag: "genesis-1-2"
    relay: "wss://thecitadel.nostr1.com"
    order: 2
  - kind: 30041
    pubkey: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"
    d_tag: "genesis-1-3"
    relay: "wss://thecitadel.nostr1.com"
    order: 3
  # ... up to Genesis 1:31

# Custom tags
custom_tags:
  - ["client", "nostrbots"]
  - ["lang", "en"]
  - ["book", "genesis"]
  - ["chapter", "1"]
  - ["testament", "old"]
