# Index Update Example - Adding Content to Existing Publication
# This shows how to append new content to an existing publication index

bot_name: "Index Update Bot"
bot_description: "Adds new content to existing publication indices with flexible positioning"

# Event kind (30040 for publication index)
event_kind: 30040

# Nostr identity configuration
npub:
  environment_variable: "NOSTR_BOT_KEY"
  public_key: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"

# Relay configuration
relays: "favorite-relays"

# Publication metadata
title: "My Technical Guide"
auto_update: true
summary: "A comprehensive technical guide with regular updates"
type: "documentation"

# Index management configuration
index_management:
  mode: "append"  # Options: create, update, append
  existing_index: "my-technical-guide-1640995200"  # D-tag of existing index
  insert_position: "after"  # Options: first, last, after, before
  reference_d_tag: "chapter-3-basics"  # Insert after this content item

# New content to add to the index
content_references:
  # Mix of different event kinds
  - kind: 30023  # Long-form article
    pubkey: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"
    d_tag: "advanced-techniques-article"
    relay: "wss://thecitadel.nostr1.com"
    order: 1
  
  - kind: 30041  # Publication content section
    pubkey: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"
    d_tag: "troubleshooting-section"
    relay: "wss://thecitadel.nostr1.com"
    order: 2
    
  - kind: 30818  # Wiki article
    pubkey: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"
    d_tag: "api-reference"
    relay: "wss://thecitadel.nostr1.com"
    order: 3
    
  - kind: 30040  # Nested index (sub-section)
    pubkey: "npub1r0r9c7upagp9s5vmxqkcjymj4mqwqw2g8m029j7pgthr2u2yl5dsn9a3r6"
    d_tag: "examples-collection"
    relay: "wss://thecitadel.nostr1.com"
    order: 4

# Topics
topics: ["technical", "guide", "documentation", "updated"]

# Custom tags
custom_tags:
  - ["client", "nostrbots"]
  - ["lang", "en"]
  - ["update_type", "content_addition"]
